default_install_hook_types: ['pre-commit', 'commit-msg']
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-ast
      - id: check-added-large-files
        exclude: 'bin|config|fastq|sra|csv|txt'
        args: ['--maxkb=2048']
      - id: check-case-conflict

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: python
        types_or: [python]
        args: ["--profile", "black", "--filter-files"]
      - id: black
        name: black
        entry: black
        language: python
        types_or: [python, pyi]
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [ python ]
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [ python ]
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [ python ]
